### ISSUE TITLE
How do I enable true color?

### ISSUE THREAD

**Issue by CrashyBang** [neeasade/xst#17]
Currently  `printf "\x1b[38;2;255;100;0mTRUECOLOR\x1b[0m\n"` (true color test) fails, I was under the understanding `st` is true color by default?

Cheers.

**Comment by neeasade** [comment]
that prints TRUECOLOR in bright orange for me, which is the intended test. True color is enabled by default. If you're in tmux or screen you might not see it -- the tmux Tc flag will be added to the info here soon, will close this issue after that.
