### ISSUE TITLE
Can not use vim in xst.

### ISSUE THREAD

**Issue by wsdjeg** [neeasade/xst#23]
even if I start vim via `vim -u NONE`.
![2017-03-27_343x255](https://cloud.githubusercontent.com/assets/13142418/24359035/a81be6ec-1335-11e7-8e48-c41c4c7bfc86.png)

**Comment by wsdjeg** [comment]
sorry, it is neovim, I have 
```
alias vim='nvim'
alias vi='/usr/bin/vim'
```
in bashrc.

**Comment by neeasade** [comment]
Perhaps try this?

https://github.com/neovim/neovim/issues/3211#issuecomment-284219798

this may be alleviated when delkey patch is reverted.

Thanks,
Nathan

**Comment by wsdjeg** [comment]
thanks will have a try.

**Comment by wsdjeg** [comment]
It works , thanks.
