### ISSUE TITLE
Is there a past functionality and if how to use it

### ISSUE THREAD

**Issue by pExeen** [neeasade/xst#24]
So I didn't know how to use the clipboard patch so i looked inside of the diff and found that to copy out of the terminal you use ctrl+t.
But can I past or not because it is the only reason I sometimes have to use urxvt.
Thanks :)

**Comment by PeterGottesman** [comment]
You should be able to paste with Shift+Insert

**Comment by pExeen** [comment]
I have to tap on shift to get insert. Can I change the shortcut ?

**Comment by neeasade** [comment]
> Can I change the shortcut ?

Currently, not here (you could fork and tweak the config.h file). The X11 paste is `S-Insert` but there also `M-S-c` and `M-S-v`(alt-shift) for copy/paste.

**Comment by pExeen** [comment]
Ok thanks :)

**Comment by mustaqimM** [comment]
If you are on `zsh`, you could do something like this:
```zsh
# Copy(C-S-C) and Paste(C-S-V) functionality for `st`
x-kill-region () {
  zle kill-region
  print -rn $CUTBUFFER | xsel -i -b
}
zle -N x-kill-region

x-yank () {
  CUTBUFFER=$(xsel -o -b </dev/null)
  zle yank
}
zle -N x-yank
bindkey -e '^X' x-kill-region
bindkey -e '^V' x-yank
```
