### ISSUE TITLE
Make first release?

### ISSUE THREAD

**Issue by Anachron** [neeasade/xst#25]
I'd like to have `xst` in Void Linux Repos, but it's only possible for projects that have a release.
Do you mind making a release? 

https://github.com/voidlinux/void-packages/issues/6247

**Comment by neeasade** [comment]
Sure. 

Before I do that I'll take a look I'll do the following. 

- revert delete patch
- sync to current http://git.suckless.org/st/log/ (we're about 8 commits behind)
- (maybe) line spacing patch. 

Will update this issue.

**Comment by neeasade** [comment]
> sync to current http://git.suckless.org/st/log/ (we're about 8 commits behind)

I've decided to do this separately from release, worried about testing big commit that separates out X code from st. 

https://github.com/neeasade/xst/releases/tag/v0.7.1

**Comment by Anachron** [comment]
Thanks a lot mate!
