### ISSUE TITLE
Line Spacing

### ISSUE THREAD

**Issue by novcn** [neeasade/xst#26]
Is it possible to configure line spacing? I have a few fonts that I would love to use, however they are rendered with excess line spacing. I have the same issue with URxvt (that I'd like to switch off from) They offer this feature, but without negative values.

**Comment by neeasade** [comment]
Not currently you might try tweaking the following in Xresources:

```
st.chscale:      1.0
st.cwscale:      1.0
```

**Comment by novcn** [comment]
Thank you! The following setting worked for me.
```st.chscale:      0.8```
