### ISSUE TITLE
Cursor color in Xresources

### ISSUE THREAD

**Issue by kyau** [neeasade/xst#30]
Would it be possible to add an option to Xresources for which color the cursor points to?

**Comment by niebieskitrociny** [comment]
So you want something separate from st.(foreground|background)? Right now if you modify those, the cursor changes too.

**Comment by kyau** [comment]
Oh, so if I get this right, the cursor is tied to foreground currently? Yea if we could change the cursor independent of that it would be awesome!

**Comment by niebieskitrociny** [comment]
More specifically, the default config.h file has them all set to color slots 256/257. Then, st.(foreground|background) will change the values of slots 256/257, which are linked to foreground/background/cursorfg/cursorbg. It shouldn't be hard to check if st.(cursorfg|cursorbg) exist, and if so set the colors independently. I can get a pull request later today with that.

**Comment by kyau** [comment]
Much appreciated!

**Comment by ccrusius** [comment]
I was about to file the exact same feature request. Adding a "mee too" since I can't upvote.

**Comment by vyp** [comment]
@ccrusius why can't you upvote? :worried:

**Comment by vyp** [comment]
Oh right, I thought you meant you couldn't thumbs up, so I curious as to why not. But yeah, thumbs ups and downs are basically voting now on github. :+1:

**Comment by niebieskitrociny** [comment]
Finally got some time to work on this, will update later today.

**Comment by niebieskitrociny** [comment]
Sorry, been struggling with my distribution for a while now, when I get the environment correct it's a five minute fix. Keep going down rabbit holes along the way right now.

**Comment by niebieskitrociny** [comment]
Code is done - if you want, give it a spin. I could go ahead and merge it but I want independent verification of it working. My setup is GuixSD and it sometimes displays strange stuff - no guarantee that since it works on my machine, it will work on yours. Assuming you are fine building it?

**Comment by kyau** [comment]
Not a problem just point me to the patch or patched source and I can give it a go.

**Comment by ccrusius** [comment]
Works for me, thanks!

**Comment by sshashank124** [comment]
Might be worth adding it to the example Xresources in the repo. I only stumbled upon this option in the issues.
